<a href="https://colab.research.google.com/github/sush995/MLProjectsLevel1/blob/main/mercedes_benz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

######################################################################
'''    Project No. 1: Mercedes-Benz Greener Manufacturing       '''
######################################################################

# Step1: Import the required libraries

In [ ]:
# linear algebra
import numpy as np
# data processing, CSV file I/O (e.g. pd.read_csv)
import pandas as pd
# for dimensionality reduction
from sklearn.decomposition import PCA

# Step2: Read the data from train.csv

In [ ]:
df_train = pd.read_csv('train.csv')
# let us understand the data
print('Size of training set: {} rows and {} columns'
      .format(*df_train.shape))
# print few rows and see how the data looks like
df_train.head()

Size of training set: 4209 rows and 378 columns

   ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1   6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2   7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0
3   9   80.62  az  t   n  f  d  ...    0    0    0     0     0     0     0
4  13   78.02  az  v   n  f  d  ...    0    0    0     0     0     0     0

[5 rows x 378 columns]

# Step3: Collect the Y values into an array

In [ ]:
# seperate the y from the data as we will use this to learn as 
# the prediction output
y_train = df_train['y'].values

# Step4: Understand the data types we have

In [ ]:
# iterate through all the columns which has X in the name of the column
cols = [c for c in df_train.columns if 'X' in c]
print('Number of features: {}'.format(len(cols)))

print('Feature types:')
df_train[cols].dtypes.value_counts()

Number of features: 376
Feature types:

int64     368
object      8
dtype: int64

# Step5: Count the data in each of the columns

In [ ]:
counts = [[], [], []]
for c in cols:
    typ = df_train[c].dtype
    uniq = len(np.unique(df_train[c]))
    if uniq == 1:
        counts[0].append(c)
    elif uniq == 2 and typ == np.int64:
        counts[1].append(c)
    else:
        counts[2].append(c)

print('Constant features: {} Binary features: {} Categorical features: {}\n'
      .format(*[len(c) for c in counts]))
print('Constant features:', counts[0])
print('Categorical features:', counts[2])

Constant features: 12 Binary features: 356 Categorical features: 8

Constant features: ['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290', 'X293', 'X297', 'X330', 'X347']
Categorical features: ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']

# Step6: Read the test.csv data

In [ ]:
df_test = pd.read_csv('test.csv')

# remove columns ID and Y from the data as they are not used for learning
usable_columns = list(set(df_train.columns) - set(['ID', 'y']))
y_train = df_train['y'].values
id_test = df_test['ID'].values

x_train = df_train[usable_columns]
x_test = df_test[usable_columns]

# Step7: Check for null and unique values for test and train sets

In [ ]:
def check_missing_values(df):
    if df.isnull().any().any():
        print("There are missing values in the dataframe")
    else:
        print("There are no missing values in the dataframe")
check_missing_values(x_train)
check_missing_values(x_test)

There are no missing values in the dataframe
There are no missing values in the dataframe

# Step8: If for any column(s), the variance is equal to zero,

In [ ]:
# then you need to remove those variable(s).
# Apply label encoder

for column in usable_columns:
    cardinality = len(np.unique(x_train[column]))
    if cardinality == 1:
        x_train.drop(column, axis=1) # Column with only one 
        # value is useless so we drop it
        x_test.drop(column, axis=1)
    if cardinality > 2: # Column is categorical
        mapper = lambda x: sum([ord(digit) for digit in x])
        x_train[column] = x_train[column].apply(mapper)
        x_test[column] = x_test[column].apply(mapper)
x_train.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

   X325  X194  X32  X222  X125  X310  ...  X123  X201  X279  X67  X171  X254
0     0     1    0     0     0     0  ...     0     0     0    0     0     0
1     0     1    0     0     0     0  ...     0     0     0    0     0     0
2     0     1    0     0     0     0  ...     0     0     1    0     0     0
3     0     1    0     0     0     0  ...     0     0     1    0     0     0
4     0     1    0     0     0     0  ...     0     0     1    0     0     0

[5 rows x 376 columns]

# Step9: Make sure the data is now changed into numericals

In [ ]:
print('Feature types:')
x_train[cols].dtypes.value_counts()

Feature types:

int64    376
dtype: int64

# Step10: Perform dimensionality reduction

In [ ]:
# Linear dimensionality reduction using Singular Value Decomposition of 
# the data to project it to a lower dimensional space.
n_comp = 12
pca = PCA(n_components=n_comp, random_state=420)
pca2_results_train = pca.fit_transform(x_train)
pca2_results_test = pca.transform(x_test)

# Step11: Training using xgboost

In [ ]:
import xgboost as xgb
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(
        pca2_results_train, 
        y_train, test_size=0.2, 
        random_state=4242)

d_train = xgb.DMatrix(x_train, label=y_train)
d_valid = xgb.DMatrix(x_valid, label=y_valid)
#d_test = xgb.DMatrix(x_test)
d_test = xgb.DMatrix(pca2_results_test)

params = {}
params['objective'] = 'reg:linear'
params['eta'] = 0.02
params['max_depth'] = 4

def xgb_r2_score(preds, dtrain):
    labels = dtrain.get_label()
    return 'r2', r2_score(labels, preds)

watchlist = [(d_train, 'train'), (d_valid, 'valid')]

clf = xgb.train(params, d_train, 
                1000, watchlist, early_stopping_rounds=50, 
                feval=xgb_r2_score, maximize=True, verbose_eval=10)

# Step12: Predict your test_df values using xgboost

p_test = clf.predict(d_test)

sub = pd.DataFrame()
sub['ID'] = id_test
sub['y'] = p_test
sub.to_csv('xgb.csv', index=False)

sub.head()

[17:17:05] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[0]	train-rmse:99.1484	valid-rmse:98.263	train-r2:-58.353	valid-r2:-67.6375
Multiple eval metrics have been passed: 'valid-r2' will be used for early stopping.

Will train until valid-r2 hasn't improved in 50 rounds.
[10]	train-rmse:81.2766	valid-rmse:80.3643	train-r2:-38.8843	valid-r2:-44.9101
[20]	train-rmse:66.7161	valid-rmse:65.7733	train-r2:-25.874	valid-r2:-29.7526
[30]	train-rmse:54.8691	valid-rmse:53.8914	train-r2:-17.1772	valid-r2:-19.6453
[40]	train-rmse:45.2471	valid-rmse:44.2232	train-r2:-11.361	valid-r2:-12.9022
[50]	train-rmse:37.4486	valid-rmse:36.3761	train-r2:-7.46723	valid-r2:-8.40622
[60]	train-rmse:31.1458	valid-rmse:30.0225	train-r2:-4.85695	valid-r2:-5.40732
[70]	train-rmse:26.0842	valid-rmse:24.915	train-r2:-3.10795	valid-r2:-3.41268
[80]	train-rmse:22.0431	valid-rmse:20.8305	train-r2:-1.93371	valid-r2:-2.08449
[90]	train-rmse:18.8467	valid-rmse:17.5968	train-r2:-1.14458	valid-r2:-1.20115
[100]	train-rmse:16.3328	valid-rmse:15.0789	train-r2:-0.610615	valid-r2:-0.616293
[110]	train-rmse:14.3975	valid-rmse:13.1482	train-r2:-0.251552	valid-r2:-0.228898
[120]	train-rmse:12.9278	valid-rmse:11.6929	train-r2:-0.009073	valid-r2:0.028089
[130]	train-rmse:11.8068	valid-rmse:10.6169	train-r2:0.158342	valid-r2:0.19873
[140]	train-rmse:10.9847	valid-rmse:9.85685	train-r2:0.271467	valid-r2:0.309349
[150]	train-rmse:10.3731	valid-rmse:9.32089	train-r2:0.350334	valid-r2:0.382416
[160]	train-rmse:9.91865	valid-rmse:8.95928	train-r2:0.406013	valid-r2:0.429405
[170]	train-rmse:9.58084	valid-rmse:8.71328	train-r2:0.445784	valid-r2:0.460309
[180]	train-rmse:9.33902	valid-rmse:8.55257	train-r2:0.473408	valid-r2:0.480033
[190]	train-rmse:9.15109	valid-rmse:8.44777	train-r2:0.494388	valid-r2:0.492699
[200]	train-rmse:9.00817	valid-rmse:8.38791	train-r2:0.510058	valid-r2:0.499862
[210]	train-rmse:8.90467	valid-rmse:8.34975	train-r2:0.521251	valid-r2:0.504403
[220]	train-rmse:8.82894	valid-rmse:8.31976	train-r2:0.52936	valid-r2:0.507956
[230]	train-rmse:8.76702	valid-rmse:8.30397	train-r2:0.535939	valid-r2:0.509822
[240]	train-rmse:8.72161	valid-rmse:8.29916	train-r2:0.540733	valid-r2:0.51039
[250]	train-rmse:8.67967	valid-rmse:8.29209	train-r2:0.54514	valid-r2:0.511224
[260]	train-rmse:8.64575	valid-rmse:8.28975	train-r2:0.548688	valid-r2:0.511499
[270]	train-rmse:8.61264	valid-rmse:8.28928	train-r2:0.552138	valid-r2:0.511555
[280]	train-rmse:8.57794	valid-rmse:8.28786	train-r2:0.55574	valid-r2:0.511722
[290]	train-rmse:8.55248	valid-rmse:8.28645	train-r2:0.558373	valid-r2:0.511889
[300]	train-rmse:8.52479	valid-rmse:8.28302	train-r2:0.561228	valid-r2:0.512292
[310]	train-rmse:8.49977	valid-rmse:8.28059	train-r2:0.563801	valid-r2:0.512579
[320]	train-rmse:8.47695	valid-rmse:8.28008	train-r2:0.566139	valid-r2:0.512639
[330]	train-rmse:8.45084	valid-rmse:8.27429	train-r2:0.568808	valid-r2:0.51332
[340]	train-rmse:8.42865	valid-rmse:8.27654	train-r2:0.571069	valid-r2:0.513055
[350]	train-rmse:8.40991	valid-rmse:8.27518	train-r2:0.572974	valid-r2:0.513215
[360]	train-rmse:8.38559	valid-rmse:8.27227	train-r2:0.57544	valid-r2:0.513558
[370]	train-rmse:8.36272	valid-rmse:8.27231	train-r2:0.577753	valid-r2:0.513553
[380]	train-rmse:8.33813	valid-rmse:8.27194	train-r2:0.580232	valid-r2:0.513597
[390]	train-rmse:8.31337	valid-rmse:8.27096	train-r2:0.582721	valid-r2:0.513712
[400]	train-rmse:8.29535	valid-rmse:8.26959	train-r2:0.584529	valid-r2:0.513873
[410]	train-rmse:8.26244	valid-rmse:8.26973	train-r2:0.58782	valid-r2:0.513856
[420]	train-rmse:8.24522	valid-rmse:8.27209	train-r2:0.589535	valid-r2:0.513579
[430]	train-rmse:8.21657	valid-rmse:8.26865	train-r2:0.592383	valid-r2:0.513983
[440]	train-rmse:8.19391	valid-rmse:8.26774	train-r2:0.594628	valid-r2:0.514091
[450]	train-rmse:8.16749	valid-rmse:8.26487	train-r2:0.597237	valid-r2:0.514427
[460]	train-rmse:8.14066	valid-rmse:8.26633	train-r2:0.59988	valid-r2:0.514256
[470]	train-rmse:8.11453	valid-rmse:8.26897	train-r2:0.602444	valid-r2:0.513946
[480]	train-rmse:8.09202	valid-rmse:8.26629	train-r2:0.604646	valid-r2:0.514261
[490]	train-rmse:8.06951	valid-rmse:8.26768	train-r2:0.606843	valid-r2:0.514098
[500]	train-rmse:8.04542	valid-rmse:8.26679	train-r2:0.609187	valid-r2:0.514202
Stopping. Best iteration:
[454]	train-rmse:8.16113	valid-rmse:8.26485	train-r2:0.597865	valid-r2:0.514429

   ID           y
0   1   82.774200
1   2   97.070511
2   3   83.028656
3   4   76.971710
4   5  112.535919


######################################################################
'''                          End                        '''
######################################################################